repos:
  - repo: local
    hooks:
      - id: scanoss-check-undeclared-code
        name: SCANOSS Check Undeclared
        entry: scanoss-check-undeclared-code
        language: python
        pass_filenames: false
        verbose: true
  - repo: local
    hooks:
      - id: test-python-version
        name: Test Python Version
        entry: which python
        language: system
        pass_filenames: false
