- id: scanoss-check-undeclared-code
  name: SCANOSS Undeclared Check
  description: Check for potential undeclared open source software in the files being commited
  entry: scanoss-check-undeclared-code
  language: python
  stages: [pre-commit, pre-push, manual]
  pass_filenames: false
  require_serial: true
  verbose: true
