repos:
  - repo: local
    hooks:
      - id: check-open-source-software
        name: check-open-source-software
        entry: python ./src/hooks/check_open_source_software.py
        language: python
        verbose: true
