name: Create a Release Package
# This workflow will create a draft release on GitHub for the tagged version

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Build Dev Package - ${{ github.ref_name }}
        run: make dev_setup

      - name: Run Local Tests
        run: |
          which scanoss-check-undeclared-code
          scanoss-check-undeclared-code --version
          scanoss-check-undeclared-code

      - name: Dev Uninstall
        run: make dev_uninstall

      - name: Create Draft Release ${{ github.ref_type }} - ${{ github.ref_name }}
        if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
