name: Build/Test Local Python Package
# This workflow will build and test the local hooks package

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Build Local Package
        run: make dev_setup

      - name: Run Local Tests
        run: |
          which scanoss-check-undeclared-code
          scanoss-check-undeclared-code --help
          scanoss-check-undeclared-code
